services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=ticketsonfire
  #     - POSTGRES_PASSWORD=fire
  #     - POSTGRES_DB=ticketsonfire
  #   container_name: postgres
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database-1.c5cvujhpvpl2.us-east-1.rds.amazonaws.com:5432/postgres
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
