service: nestjs-server-api
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: api
  region: us-east-1
  iam:
    role: ${env:AWS_ROLE} 
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

package:
  include:
    - node_modules/@vendia/serverless-express/**
