service: nestjs-server-api
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: api
  region: us-east-1
  iam:
    role: arn:aws:iam::911970324056:role/LabRole
  environment:
    DATABASE_URL: 'postgresql://postgres:postgres@database-1.c5cvujhpvpl2.us-east-1.rds.amazonaws.com:5432/postgres'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

package:
  include:
    - node_modules/@vendia/serverless-express/**
