name: Test

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 

    - name: Install Dependencies
      run: npm install

    # - name: Generate Prisma Client
    #   run: npx prisma generate
      
    - name: Build Application
      run: npm run build

    - name: Install Serverless Framework
      run: npm -g install serverless@3

    - name: Install Serverless Offline
      run: serverless plugin install -n serverless-offline
      
    - name: Serverless Deploy
      run: serverless deploy
